export * from "./admin/dashboard/Dashboard";
export * from "./admin/usuarios/ListagemDeUsuario";
export * from "./admin/usuarios/DetalheDeUsuario";
export * from "./admin/usuarios/Cursos";
export * from "./admin/cursos/ListagemDeCurso";
export * from "./admin/cursos/DetalheDeCurso";
export * from "./admin/aulas/ListagemDeAula";
export * from "./admin/aulas/DetalheDeAula";
export * from "./admin/login/LoginPage";
export * from "./user/HomePage/HomePage";
export * from "./user/CoursePage/CoursePage";
export * from "./user/Login/LoginPage";
export * from "./user/Dashboard/DashboardUser"